controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_brand:
      type: joint_state_broadcaster/JointStateBroadcaster


# diff_cont:
#   ros__parameters:
#     update_rate: 50        # Frecuencia de actualización (Hz)
#     publish_rate: 50.0        # Frecuencia de publicación de la odometría (Hz)
#     cmd_vel_timeout: 0.5      # Tiempo de espera para considerar que se perdió la señal
#     left_wheel_names: ["front_left_wheel_joint", "back_left_wheel_joint"]
#     right_wheel_names: ["front_right_wheel_joint", "back_right_wheel_joint"]
#     wheel_separation: 1.2     # Distancia entre el centro de la rueda izquierda y la derecha [m]
#     wheel_radius: 0.3         # Radio de las ruedas [m]
#     # base_frame_id: "base_link" # Nombre del frame del robot 
#     # odom_frame_id: "odom"      # Nombre del frame de la odometría
#     # wheels_per_side: 2
#     linear:
#       x: 3.0
#       y: 0.0
#     angular:
#       z: 1.0
#     # Si no usas stamped_velocity, se calculan las velocidades a partir de la cinemática
#     use_stamped_velocity: false



# # joint_broad:
# #   ros__parameters:

diff_cont:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "back_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "back_right_wheel_joint"]

    wheel_separation: 0.40
    wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.02

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: -1.0

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.0
    linear.x.min_velocity: 0.0
    linear.x.max_acceleration: 0.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.0
    angular.z.min_velocity: 0.0
    angular.z.max_acceleration: 0.0
    angular.z.min_acceleration: 0.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0