global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: "map"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    publish_frequency: 2.0
    rolling_window: false
    resolution: 0.05
    static_map: false
    # Usamos el tópico del OctoMap proyectado
    map_topic: "/projected_map"
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      # Indicamos que la fuente de observación es el OctoMap
      observation_sources: "octomap"
      octomap:
        topic: "/projected_map"
        sensor_frame: "base_link"  # Asegúrate de que sea el frame correcto para tus datos
        data_type: "PointCloud2"
        clearing: true
        marking: true
        obstacle_range: 3.0
        raytrace_range: 3.5
        expected_update_rate: 1.0
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.55
      cost_scaling_factor: 10.0

local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: "odom"
    robot_base_frame: "base_link"
    update_frequency: 10.0
    publish_frequency: 2.0
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05
    static_map: false
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: "octomap"
      octomap:
        topic: "/projected_map"
        sensor_frame: "base_link"
        data_type: "PointCloud2"
        clearing: true
        marking: true
        obstacle_range: 3.0
        raytrace_range: 3.5
        expected_update_rate: 1.0
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.55
      cost_scaling_factor: 10.0
