left_front_wheel_joint:
  type: effort_controllers/JointPositionController
  joint: left_front_wheel_joint
  pid: {p: 10.0, i: 0.1, d: 1.0}

right_front_wheel_joint:
  type: effort_controllers/JointPositionController
  joint: right_front_wheel_joint
  pid: {p: 10.0, i: 0.1, d: 1.0}

left_back_wheel_joint:
  type: effort_controllers/JointPositionController
  joint: left_back_wheel_joint
  pid: {p: 10.0, i: 0.1, d: 1.0}

right_back_wheel_joint:
  type: effort_controllers/JointPositionController
  joint: right_back_wheel_joint
  pid: {p: 10.0, i: 0.1, d: 1.0}
