joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

wheel_controller:
  type: effort_controllers/JointEffortController
  joint: Direction_right_front
  pid: {p: 100.0, i: 0.01, d: 0.1}
